export const USUARIO_AUTENTICADO = "USUARIO_AUTENTICADO";
export const LIMPIAR_ALERTA = "LIMPIAR_ALERTA";

export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';